export const ADD_CARD = "ADD_CARD";
export const EDIT_CARD = "EDIT_CARD";
export const REMOVE_CARD = "REMOVE_CARD";
export const MOVE_CARD = "MOVE_CARD";
export const CREATE_CANVAS = "CREATE_CANVAS";
export const ARCHIVE_CANVAS = "ARCHIVE_CANVAS";
export const OPEN_CANVAS = "OPEN_CANVAS";

export default {
    ADD_CARD, EDIT_CARD, REMOVE_CARD, MOVE_CARD, CREATE_CANVAS, ARCHIVE_CANVAS, OPEN_CANVAS    
};